import type { VisualizarOS } from "./PesquisaView";

export const mockOS: VisualizarOS = {
  id: 0,
  DATA_SOLICITACAO: "",
  PREVISAO_ENTREGA: "",
  VENDEDOR: { first_name: "" },
  CLIENTE: { id: 0, nome: "" },
  SERVICO: "",
  LABORATORIO: "",
  OD_ESF: "",
  OD_CIL: "",
  OD_EIXO: "",
  OE_ESF: "",
  OE_CIL: "",
  OE_EIXO: "",
  AD: "",
  DNP: "",
  P: "",
  DPA: "",
  DIAG: "",
  V: "",
  H: "",
  ALT: "",
  ARM: "",
  MONTAGEM: "",
  LENTES: "",
  ARMACAO: "",
  OBSERVACAO: "",
  FORMA_PAG: "A",
  VALOR: "",
  QUANTIDADE_PARCELA: 1,
  ENTRADA: "",
  STATUS: "A",
};
